name: Nightly

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build Artifacts
      run: ./publish.ps1
      shell: pwsh
      env:
        CLI_VERSION: ${{ github.ref }}
        SKIP_LINUX: true
        SKIP_MACOS: true

    - name: Run for CLI
      run: .\actions-stats-windows-amd64.exe get-runs --org github --repo gh-gei --workflow-name CI
      working-directory: ./dist/win-x64/
      shell: pwsh
      env:
        GH_PAT: ${{ secrets.CLI_PAT }}
        SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}

    - name: Run for Octoshift
      run: .\actions-stats-windows-amd64.exe get-runs --org github --repo Octoshift --workflow-name "Regression Tests"
      working-directory: ./dist/win-x64/
      shell: pwsh
      env:
        GH_PAT: ${{ secrets.CLI_PAT }}
        SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
        GEI_DEBUG_MODE: 'true'
        
    - name: Upload test logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: nightly-logs
        path: dist/**/*.log

    - name: Test Logs
      if: always()
      run: Get-ChildItem . -Filter *.octoshift.log -Recurse | ForEach-Object { Get-Content -Path $_.FullName }
      working-directory: ./dist
      shell: pwsh

    - name: Test Logs (Verbose)
      if: always()
      run: Get-ChildItem . -Filter *.octoshift.verbose.log -Recurse | ForEach-Object { Get-Content -Path $_.FullName }
      working-directory: ./dist
      shell: pwsh
